package com.cibo.provenance

import java.time.Instant

/**
  * Created by ssmith on 10/23/17.
  *
  * This class poses as an actual GitBuildInfo, but with values that do not change over time.
  *
  * Apps will have a BuildInfo generated by SbtBuildInfo that captures the source control and build information.
  * This is an alternative used as a placeholder in test cases for this library, and for library users.
  *
  * Note: This is distinct from `NoBuildInfo`, used for internal things that exist outside of applications.
  * This should be used only for tests.
  *
  */
object BuildInfoDummy extends BuildInfoGit {
  def name: String = "DUMMY-NAME"
  def version: String = "DUMMY-VERSION"
  def scalaVersion: String = "DUMMY-SCALA-VERSION"
  def sbtVersion: String = "DUMMY-SBT-VERSION"

  lazy val startTime: Instant = Instant.parse("1955-11-12T22:04:00.000Z") // we don't need roads

  def gitBranch: String = "DUMMY-BRANCH"
  def gitUncommittedChanges: Boolean = false
  def gitHash: String = "DUMMY-COMMIT"
  def gitHashShort: String = "DUMMYCOM"
  def gitCommitAuthor: String = "DUMMY-AUTHOR"
  def gitCommitDate: String = "1919-01-01T00:01:02.000Z"
  def gitMessage: String = "DUMMY-DESCRIBE"

  lazy val builtAtString: String = startTime.toString
  lazy val builtAtMillis: Long = startTime.toEpochMilli
}


